name: Chairs
version: ${pluginversion}
description: Let players sit on blocks.
website: http://dev.bukkit.org/bukkit-plugins/chairsreloaded/
authors: [jkcclemens, spoothie, cnaude]
main: com.cnaude.chairs.Chairs
commands:
    chairs:
        description: Various commands for Chairs.
        usage: |
          /<command> reload - reloads the configuration
          /<command> off  - disable chairs for self
          /<command> on - enable chairs for self
